name: file_encryptify
description: "A cross-platform tool to encrypt & decrypt your file(s)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluent_ui: ^4.4.0
  system_theme: ^2.3.1
  path_provider: ^2.1.3
  drift: ^2.15.0
  get: ^4.6.6
  get_storage: ^2.1.1
  file_cryptor: ^0.0.3
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
